services:
  db:
    image: mariadb:10.11
    container_name: student_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: student_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  app:
    image: custom-php
    container_name: student_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["sleep", "infinity"]
